feat(cvsb-15219): added in name swap logic and unit tests that corres…
dvsa/cvs-tsk-cert-gen pull request #77
Opened 2021-09-16 09:35 UTC by Daniel-Searle

## KT - (BE) Reverse tester name on certificates

When a comma is present within the tester name attribute in Azure AD, the name will be flipped to present 'Forename Surname' on the certificate
[link to ticket number](https://jira.dvsacloud.uk/browse/CVSB-15219)

## Checklist

- [ ] Branch is rebased against the latest develop/common
- [ ] Necessary `id` required prepended with `"test-"` have been checked with automation testers and added
- [ ] Code and UI has been tested manually after the additional changes
- [ ] PR title includes the JIRA ticket number
- [ ] Squashed commits contain the JIRA ticket number
- [ ] Link to the PR added to the repo
- [ ] Delete branch after merge

2021-09-16 10:39 UTC, m-coslett commented on src/services/CertificateGenerationService.ts
> +      [nameArrayList[0], nameArrayList[1]] = [nameArrayList[1], nameArrayList[0]];
this line is not needed as the nameArrayList values are never used again

2021-09-16 10:51 UTC, m-coslett requested changes

2021-09-16 10:51 UTC, m-coslett commented on src/services/CertificateGenerationService.ts
> +      name = name.split(", ").reverse().join(", ");
Please check the AC's with a BA.  This code will return "Melanie, Coslett" which matches what the AC's state the logic should be, but not the example.  I don't think there should be a comma between the first name(s) and surname.

2021-09-16 10:51 UTC, m-coslett commented on src/services/CertificateGenerationService.ts
> +      [nameArrayList[0], nameArrayList[1]] = [nameArrayList[1], nameArrayList[0]];
this line is not needed as the nameArrayList values are never used again

2021-09-16 11:22 UTC, JonLazariniDD commented on src/services/CertificateGenerationService.ts
> +      [nameArrayList[0], nameArrayList[1]] = [nameArrayList[1], nameArrayList[0]];
I will leave it to you to decide but we could further simplify the code and use reduce some strings 'are' also arrays in Js.
See reduce https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

```js
// I wouldn't necessarily mutate the payload
// Will flip lastName and firstName assuming the separator is the , between them
let name = testResult.testerName.split(",").reduce((curr, acc) => `${acc.trim()} ${curr}`)
...
testResult.testerName = name
...
```
One point which has not been clarified when asked in the ticket is whether the name formats can have middle names, etc..
e.g. can we have lastName, firstName, MiddleName, etc.. ?

Also even if the coverage is about what is agreed with DVSA Standard, I suggest we try to aim for 100% and add coverage for this function.
We could import it from an util.js file where this function would be added and we add the coverage for the util.js (and Name switcher function) and also checked that the function is called in generatePayload function

2021-09-16 11:22 UTC, JonLazariniDD commented on tests/resources/queue-event-pass.json
> +      "messageAttributes": {},
Can we have such data in prod for `testerName`? also it seems to be that the payload for testerName is FirstName, MiddleName, LastName

2021-09-16 11:22 UTC, JonLazariniDD commented on tests/unit/certGen.unitTest.ts
> +                IssuersName: "Dev1, CVS",
I think there are ACs (3 & 4?) which are not covered, I believe we have 4 scenarios but we have 2 unit tests. I would need a catch up on AC1 & 2 please when you have time.
We could use this jest tables to test the permutations: https://jestjs.io/docs/26.x/api#2-testeachtablename-fn-timeout

2021-10-12 10:19 UTC, cb-cs approved these changes

2021-10-12 10:20 UTC, m-coslett submitted a review, later dismissed

2022-04-13 07:49 UTC, closed without merging